const dialog=document.querySelector('#detail-dialog'),detail=document.querySelector('#detail-content');
const P={
'project-v8':{k:'02 / PERSONAL PROJECT',d:'JANUARY–MARCH 2026',t:'V8 Engine Internal Combustion Design',lead:'A personal CAD project exploring how an engine’s components come together as a moving mechanical assembly.',role:'Personal project',tools:'Onshape · SolidWorks · Parametric CAD',focus:'Assembly & motion',left:'<p>Built a parametric, multi-component engine assembly and explored the relationships between pistons, connecting components, and valve motion.</p>',right:'<ul><li>Parametric part modeling and multi-component assembly.</li><li>Piston subassemblies and motion validation.</li><li>Tangent mates and cam–valve motion exploration.</li></ul>',note:'Tangent-mate behavior and full 360° motion were areas of troubleshooting. This portfolio does not claim a fully resolved cam–valve mechanism or a built, running engine.'},
'project-pump':{k:'03 / COURSE PROJECT',d:'FALL 2025',t:'Water Pump Design & Fabrication',lead:'A bucket-and-gear conveyor concept for moving water vertically and horizontally using animal-powered input.',role:'Course project',tools:'Onshape · CAD · Mechanism design',focus:'Water transport',left:'<p>Explored a mechanism for transporting water using buckets and gears, with input from an animal walking in a circular path.</p>',right:'<ul><li>CAD modeling of the water-transport concept.</li><li>Bucket-and-gear conveyor arrangement.</li><li>Gears, shafts, buckets, and support structures.</li></ul>',note:'The belt was not functional in the CAD model. Fabrication details and test results are not claimed here.'}}
function projectView(p){return `<div class="detail-inner"><div class="detail-kicker"><span>${p.k}</span><span>${p.d}</span></div><h2 id="detail-title">${p.t}</h2><p class="detail-lead">${p.lead}</p><dl class="detail-meta"><div><dt>CONTEXT</dt><dd>${p.role}</dd></div><div><dt>TOOLS</dt><dd>${p.tools}</dd></div><div><dt>FOCUS</dt><dd>${p.focus}</dd></div></dl><div class="detail-grid"><div><h3>The design challenge</h3>${p.left}</div><div><h3>What I worked on</h3>${p.right}</div></div><div class="detail-note"><h3>KNOWN / DOCUMENTED LIMITATION</h3><p>${p.note}</p></div><div class="detail-nav"><a href="#work">← All selected work</a><a href="#about">Background & contact →</a></div></div>`}
function toolkit(){return `<div class="detail-inner"><div class="detail-kicker"><span>04 / TECHNICAL TOOLKIT</span><span>CODE & COMPUTATION</span></div><h2 id="detail-title">Another way to work through a problem.</h2><p class="detail-lead">Python and JavaScript complement my CAD and analytical background, alongside Microsoft Excel, linear algebra, differential equations, and statistics.</p><div class="toolkit-placeholder"><div><strong>{ }</strong><h3>Selected code examples are coming.</h3><p>This space stays intentionally conservative until a specific script, assignment, repository, inputs, and outputs are documented.</p></div></div></div>`}
function resume(){return `<div class="detail-inner"><div class="detail-kicker"><span>05 / RÉSUMÉ OVERVIEW</span><span>SUMMER 2027</span></div><div class="resume-heading"><h2 id="detail-title">Devan Calabrese</h2><button class="outline-button" onclick="window.print()">Print / save as PDF ↗</button></div><p class="resume-contact">Mechanical Engineering Student · Cleveland / Columbus, OH<br><a href="mailto:Calabrese.90@osu.edu">Calabrese.90@osu.edu</a></p><div class="resume-section"><h3>Education</h3><div class="resume-item"><h4>The Ohio State University — B.S. Mechanical Engineering</h4><p>Expected May 2029 · GPA 3.86 · Dean’s List Spring 2026</p></div><div class="resume-item"><h4>University of Cincinnati — Mechanical Engineering coursework</h4><p>Fall 2025 · GPA 3.92 · Dean’s List Fall 2025</p></div></div><div class="resume-section"><h3>Selected projects</h3><p>V8 Engine Internal Combustion Design · Water Pump Design & Fabrication</p></div><div class="resume-section"><h3>Skills</h3><p>Onshape · SolidWorks · Python · JavaScript · Microsoft Excel · Parametric CAD · Mechanical systems design</p></div></div>`}
function route(){const r=location.hash.slice(1);if(P[r]||r==='project-code'||r==='resume'){detail.innerHTML=P[r]?projectView(P[r]):r==='project-code'?toolkit():resume();if(!dialog.open)dialog.showModal();document.body.classList.add('dialog-open')}else if(dialog.open){dialog.close();document.body.classList.remove('dialog-open')}}
document.querySelector('#close-dialog').onclick=()=>{history.replaceState(null,'',location.pathname+'#work');route()};dialog.addEventListener('cancel',e=>{e.preventDefault();document.querySelector('#close-dialog').click()});window.addEventListener('hashchange',route);
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});let n=0;document.querySelectorAll('[data-category]').forEach(c=>{c.hidden=b.dataset.filter!=='all'&&b.dataset.filter!==c.dataset.category;if(!c.hidden)n++});document.querySelector('#filter-count').textContent=`${n} ${n===1?'entry':'entries'}`});
const tabs=[...document.querySelectorAll('[role=tab]')];tabs.forEach(t=>t.onclick=()=>tabs.forEach(x=>{const a=x===t;x.setAttribute('aria-selected',String(a));x.tabIndex=a?0:-1;document.getElementById(x.getAttribute('aria-controls')).hidden=!a}));
document.querySelector('#copy-email').onclick=async()=>{const s=document.querySelector('#copy-status');try{await navigator.clipboard.writeText('Calabrese.90@osu.edu');s.textContent='Email copied.'}catch{s.textContent='Select the email address to copy it.'}};route();